name: Format Documents

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # You can specify the Node.js version here

    - name: Install dependencies
      run: npm install prettier

    - name: Run script
      run: npx prettier src/. --write

    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit changes
      run: |
        git add app/. backend /. components/. lib/. types/. prisma/. public/.
        git commit -m "Format"
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true